DOWNS_BLACK = {
    "language": "pt",
    "items_language": "en",
    "translation_note": "Os itens das escalas foram mantidos no idioma original pela falta de trabalhos de tradução e adaptação cultural.",
    "reference": "Downs SH, Black N. The feasibility of creating a checklist for the assessment of the methodological quality both of randomised and non-randomised studies of health care interventions. Journal of Epidemiology & Community Health. 1998;52(6):377–384. doi:10.1136/jech.52.6.377.",
    "id": "db",
    "family": "Downs and Black",
    "name": "Downs and Black Checklist",
    "meta": "27 itens · ECR e estudos observacionais",
    "type": "db",
    "items": [
        {"num": "1", "domain": "Reporting", "text": "Is the hypothesis/aim/objective of the study clearly described?"},
        {"num": "2", "domain": "Reporting", "text": "Are the main outcomes to be measured clearly described in the Introduction or Methods section?"},
        {"num": "3", "domain": "Reporting", "text": "Are the characteristics of the patients included in the study clearly described?"},
        {"num": "4", "domain": "Reporting", "text": "Are the interventions of interest clearly described?"},
        {"num": "5", "domain": "Reporting", "text": "Are the distributions of principal confounders in each group of subjects to be compared clearly described?"},
        {"num": "6", "domain": "Reporting", "text": "Are the main findings of the study clearly described?"},
        {"num": "7", "domain": "Reporting", "text": "Does the study provide estimates of random variability for the main outcomes?"},
        {"num": "8", "domain": "Reporting", "text": "Have all important adverse events that may be a consequence of the intervention been reported?"},
        {"num": "9", "domain": "Reporting", "text": "Have the characteristics of patients lost to follow-up been described?"},
        {"num": "10", "domain": "Reporting", "text": "Have actual probability values been reported for the main outcomes?"},
        {"num": "11", "domain": "External validity", "text": "Were the subjects asked to participate in the study representative of the entire population from which they were recruited?"},
        {"num": "12", "domain": "External validity", "text": "Were those subjects who were prepared to participate representative of the entire population from which they were recruited?"},
        {"num": "13", "domain": "External validity", "text": "Were the staff, places, and facilities where the patients were treated representative of usual treatment?"},
        {"num": "14", "domain": "Internal validity - Bias", "text": "Was an attempt made to blind study subjects to the intervention they received?"},
        {"num": "15", "domain": "Internal validity - Bias", "text": "Was an attempt made to blind those measuring the main outcomes of the intervention?"},
        {"num": "16", "domain": "Internal validity - Bias", "text": "If any of the results of the study were based on 'data dredging', was this made clear?"},
        {"num": "17", "domain": "Internal validity - Bias", "text": "Do the analyses adjust for different lengths of follow-up or comparable time periods?"},
        {"num": "18", "domain": "Internal validity - Bias", "text": "Were the statistical tests used to assess the main outcomes appropriate?"},
        {"num": "19", "domain": "Internal validity - Bias", "text": "Was compliance with the intervention/s reliable?"},
        {"num": "20", "domain": "Internal validity - Bias", "text": "Were the main outcome measures used accurate, valid and reliable?"},
        {"num": "21", "domain": "Internal validity - Confounding", "text": "Were the participants in different groups recruited from the same population?"},
        {"num": "22", "domain": "Internal validity - Confounding", "text": "Were the participants in different groups recruited over the same period?"},
        {"num": "23", "domain": "Internal validity - Confounding", "text": "Were study subjects randomized to intervention groups?"},
        {"num": "24", "domain": "Internal validity - Confounding", "text": "Was randomized intervention assignment concealed?"},
        {"num": "25", "domain": "Internal validity - Confounding", "text": "Was there adequate adjustment for confounding?"},
        {"num": "26", "domain": "Internal validity - Confounding", "text": "Were losses of patients to follow-up taken into account?"},
        {"num": "27", "domain": "Power", "text": "Did the study have sufficient power or report a power calculation?"}
    ],
    "options": ["Yes", "No", "Unable to determine", "Partial"]
}
